name: CI Pipeline - Docker Build

# 1. The Trigger: When should this pipeline run?
on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    # 2. The Runner: What kind of computer do we need?
    runs-on: ubuntu-latest

    # 3. The Steps: What exactly should the computer do?
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t data-pipeline-app .
        
      - name: Test the Container
        run: docker run data-pipeline-app